name: Android CI

on:
  schedule:
  - cron: "1/2 * * * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout to Branch
      uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout to Branch
#       uses: actions/checkout@v3
#     - name: set up JDK 17
#       uses: actions/setup-java@v3
#       with:
#         java-version: '17'
#         distribution: 'temurin'
#         cache: gradle
#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
#     - name: Run Linter and Test
#       run: ./gradlew check
#     - name: Upload Reports
#       uses: actions/upload-artifact@v2
#       with:
#         name: Test-Reports
#         path: app/build/reports
#       if: always()
  
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout to Branch
#       uses: actions/checkout@v3
#     - name: Docker Build & Push Action
#       uses: mr-smithers-excellent/docker-build-push@v6.2
#       with:
#         image: maniyarpawan/my-demo-cicd-app-image
#         tags: cicd-docker-image-tag
#         registry: docker.io
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
    
